### ISSUE TITLE
Currently example can not work in pip release version

### ISSUE THREAD

**Issue by mike820324** [njsmith/h11#12]
Hello, 
Recently I'm trying to use h11 to rewrite our proxy server. When I'm using h11 with master branch. Everything works well. 
However, when I use ```pip install h11``` to install h11 from pypi, the original code will raise an exception saying that **Connection object has no attribute called 'next_event'**

It seems like there are some major api changes between v0.5.0 and v0.5.0-dev. However, the readthedoc page for h11 and the examples can only works in v0.5.0-dev.

Is there any schedule to release v0.5.0-dev or v0.6.0 to pypi?
Thank you.

**Comment by njsmith** [comment]
Sorry about that -- [I've been a bit behind on things recently](https://vorpus.org/blog/emerging-from-the-underworld/). I just pushed 0.6.0 to pypi though, so this should be sorted now.
