### ISSUE TITLE
Chunk extensions

### ISSUE THREAD

**Issue by Lukasa** [njsmith/h11#26]
Well, you predicted it from #19! And here it is.

Right now, amazingly, urllib3 actually tests that it can handle chunk extensions. This is the first I have seen that demonstrates that we actually do it, but here we are.

I am *open* to being told that we should drop that support, but I wanted to ask whether you think it's worth doing either of the following two things:

1. Fully supporting chunk extensions.
2. Merely *tolerating* them (ignoring them if they are received)

**Comment by njsmith** [comment]
Currently h11 tolerates chunk extensions (parses their edges, then discards
the contents). Does urllib3 actually have an API to expose these to the
user currently?

**Comment by Lukasa** [comment]
No, but I have a test that is failing that sends them. I assumed this was merely a lack of tolerance on h11's part, but I'll double-check and get back to you: presumably that test is failing for some other reason.

**Comment by Lukasa** [comment]
Ah, ok, nevermind: this is an artefact of the way the tests work.

**Comment by njsmith** [comment]
Best kind of bug report :-)
