### ISSUE TITLE
SSL Error broke current docs build

### ISSUE THREAD

**Issue by danielballan** [njsmith/h11#36]
Everything in [the basic client section](https://h11.readthedocs.io/en/latest/basic-usage.html#a-basic-client-object) is broken because of this error that occurred while initializing `client`.

```
SSLError: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:645)
```

Sorry that this is an issue and not a PR. I don't have much experience with SSL in Python. It's possible that this is a transient error.

**Comment by njsmith** [comment]
Thanks for the heads-up! Turns out there was an actual bug there...
