### ISSUE TITLE
Docs cut off in the “Flow control details” section

### ISSUE THREAD

**Issue by vfaronov** [njsmith/h11#37]
The “[Details of our HTTP support for HTTP nerds](http://h11.readthedocs.io/en/latest/supported-http.html)” section of the docs seems to be cut off in the middle of a sentence:

> First, pause handling is actually identical for both the client and server

**Comment by nateprewitt** [comment]
It looks like this wasn't completed when initially pushed. The first instance of it is in 2f68f17 which ends with that sentence.

**Comment by njsmith** [comment]
Huh. I bet I had some really interesting insights to impart there. No idea what they were at this point though... I just deleted that section for now :-).
