### ISSUE TITLE
h11 does not prevent response splitting

### ISSUE THREAD

**Issue by vfaronov** [njsmith/h11#39]
Given how many checks h11 enforces (such as `Host` on HTTP/1.1 requests), I was surprised to see that it does not prevent [response splitting](https://tools.ietf.org/html/rfc7230#section-9.4):

```
import h11
conn = h11.Connection(our_role=h11.SERVER)
data = conn.send(h11.Response(
    status_code=200,
    headers=[(b'Content-Type', b'text/plain\r\nContent-Length: 0\r\n\r\n'
                               b'HTTP/1.1 500 Internal Server Error')]))
print(data.decode())
```

This prints:

```
HTTP/1.1 200 
content-type: text/plain
Content-Length: 0

HTTP/1.1 500 Internal Server Error
connection: close


```

I guess this should be easy to prevent in h11. This is not a problem for me though, just a suggestion.

**Comment by njsmith** [comment]
This was fixed by #27 :-). On current master I get `LocalProtocolError: Illegal header value b'text/plain\r\nContent-Length: 0\r\n\r\nHTTP/1.1 500 Internal Server Error'`

I should probably roll a release one of these days...
