### ISSUE TITLE
Cyrillic error

### ISSUE THREAD

**Issue by wku** [njsmith/h11#48]
send(h11.Request(method="GET", target="/get?ttt=ЛДОР",   headers=[("Host", "httpbin.org"),   ("Connection", "close")]))
...
  File "/home/wku/anaconda3/lib/python3.6/site-packages/h11/_util.py", line 119, in bytesify
    s = s.encode("ascii")
UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-12: ordinal not in range(128)

**Comment by njsmith** [comment]
Yes, URLs on the wire (and h11 is a wire-level library) have to be ascii. Probably you want to encode the target to utf-8, and then percent-encode all the bytes that have their high bit set. See, for example: https://hyperlink.readthedocs.io/en/latest/design.html#a-tale-of-two-representations

Generally h11 wants `bytes` objects; it also accepts `str` for convenience in examples and things, but requires the `str` be pure-ASCII to avoid mistakes.
