### ISSUE TITLE
Provide trio http server example

### ISSUE THREAD

**Issue by parity3** [njsmith/h11#49]
I can't find a trio example of an http server along side the curio. I suspect it's going to be similar to curio, so not much work here. Author probably has this lying around somewhere. It would be great to see in the repo!

**Comment by njsmith** [comment]
There's a PR in #46 that I think should work. (I made some tweaks and didn't test them, so it's probably my fault if it doesn't.) I've been trying to get trio's high level networking apis finished first before worrying too much about the h11 example :-)

**Comment by parity3** [comment]
Maybe it would be good to implement an example using [python-effect](https://github.com/python-effect/effect-examples/tree/master/http) to be future-proof of any high-level networking api changes? I haven't used python-effect but I'm considering using it (along with trio) for a small distributed tasklist work queue project. Of course if I ever start on this I'll be happy to PR it.

**Comment by njsmith** [comment]
In the case I don't think it would simplify anything – we'd just have to update the wrapper code instead :-). And since the goal here is to have a simple example of how h11 and I/O can be put together, it's probably not the place to add a whole new library in between them.

**Comment by parity3** [comment]
Ok. I finally took a deep dive into the code. Ya I am starting to realize that separating out the async lib calls from all other logic (using python-effect) has a major cost which is readability/complexity, particularly in light of the fact that trio is trying NOT to make callbacks/futures/etc the default way to solve a problem.

You already mostly have the base calls (send, next_event, shutdown_and_clean_up) separated out in a wrapper, but abstracting the timeout scopes kind of nullify one of trio's more powerful advantages above other libraries in my opinion.

You can close this unless we just want to keep it open til after the high level APIs become more finalized (would you expect the APIs to mature this year?). But we also have the PR so kinda redundant either way.

**Comment by njsmith** [comment]
Done in #46

**Comment by jmehnle** [comment]
I wish you hadn't removed the `curio` example. It's useful.

**Comment by njsmith** [comment]
I'm sorry you feel that way. The trio and curio examples are so similar that I don't think having both adds much information about how to use h11 (which is the point of those examples), and so I had to make a judgment call and pick one. And, well, unsurprisingly, I prefer trio to curio for various reasons, that's why trio exists :-). The curio example is still available in the git history, or in the readthedocs documentation for older versions.

**Comment by pquentin** [comment]
Thank you for your kindness @njsmith!
