### ISSUE TITLE
5xx response after Expect: 100-continue brings states out of sync

### ISSUE THREAD

**Issue by Nikratio** [njsmith/h11#52]
I'm looking at the following code:

```
        while True:
            event = await self.server.next_event()
            log.debug('received %s', type(event))
            if not isinstance(event, h11.Data):
                break
        assert isinstance(event, h11.EndOfMessage)

        log.debug('state is %s', self.server.h11.our_state)
```

Here, self.server.h11 is an h11 object with role=h11.CLIENT, and self.server is a thin wrapper to implement I/O with trio. When I run this code, I sometimes get the following log messages:

```
14:19:16.517 DEBUG    gruagach.server.handle_passthrough: (conn 11) received <class 'h11._events.Response'>
14:19:16.518 DEBUG    gruagach.server.handle_passthrough: (conn 11) received <class 'h11._events.Data'> 
14:19:16.518 DEBUG    gruagach.server.handle_passthrough: (conn 11) received <class 'h11._events.EndOfMessage'> 
14:19:16.518 DEBUG    gruagach.server.handle_passthrough: (conn 11) state is SEND_BODY
```

I don't understand how this can possibly happen. How can the state be SEND_BODY when the most recenly received event is EndOfMessage?

**Comment by Nikratio** [comment]
Ok, progress: this happens when we send a request with `Expect: 100-continue`, and the server then replies with an error request code. In this case the client should not actually send the body, so we end up with `h11.our_state == SEND_BODY` and `h11.their_state == MUST_CLOSE`.

That doesn't seem right to me though. I think in this example the server send the error with `Connection: close`, but if this is not the case then there ought to be a way to re-use this connection...

**Comment by Nikratio** [comment]
Note that we can't simply send a `h11.EndOfMessage` to the server, because we may have declared a Content-Length so that not sending the expected amount of body data will raise a `LocalProtocolError`.

**Comment by Nikratio** [comment]
Duplicate of issue #43

**Comment by njsmith** [comment]
Yeah, receiving an `EndOfMessage` will certainly change `their_state` to something besides `SEND_BODY`, but it doesn't change `our_state`; that only happens when we *send* `EndOfMessage`. (And I answered the rest on #43; it's a bit confusing but I think in this case h11 is accurately encoding the confusing way that HTTP works.)
