### ISSUE TITLE
Example code has sendfile where send is needed

### ISSUE THREAD

**Issue by gareth-rees** [njsmith/h11#54]
The [API discussion of sendfile support](https://h11.readthedocs.io/en/latest/api.html#sendfile) contains the example code:
```
def send_data(sock, data):
    if isinstance(data, FilePlaceholder):
        # socket.sendfile added in Python 3.5
        sock.sendfile(data.file, data.offset, data.count)
    else:
        sock.sendfile(data)
```
The second call to `socket.sendfile` looks like a mistake for `socket.send`.

**Comment by njsmith** [comment]
Nice catch, thanks!
